config/routes.rb
Rails.application.routes.draw do
  root "pages#landing"

  resources :projects, only: [:index, :show, :create, :new] do
    resources :tasks
  end

  resources :tasks, only: [:index, :show, :create, :new] do
    resources :comments
  end

  resources :comments, only: [:index, :show, :create, :new]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task

  validates :body, presence: true
  validates :author_name, presence: true

  delegate :project, to: :task
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true

  has_many :tasks, dependent: :destroy
  has_many :comments, through: :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :priority, presence: true, numericality: {
    in: 1..5,
    message: "must be between 1 and 5"
  }

  enum :status, {
    todo: 0,
    in_progress: 1,
    done: 2
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @task, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        @comments = @task.comments
        format.html { render "tasks/show", status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_path, notice: "Comment was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.expect(comment: [ :body, :author_name, :task_id ])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @params = params
    @task = Task.new
    @tasks = @project.tasks
    @tasks = @tasks.where(status: @params[:status]) if @params[:status].present?
    @tasks = @tasks.where(priority: @params[:priority]) if @params[:priority].present?
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, notice: "Project was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.expect(project: [ :name, :description ])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @comments = @task.comments
    @comment = Comment.new
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @project, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render "projects/show", status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    @project = Project.find(params[:project_id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @project, notice: "Task was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render "projects/show", status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_path, notice: "Task was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.expect(task: [ :title, :status, :due_date, :priority, :project_id ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

  <p>
    <strong>Author name:</strong>
    <%= comment.author_name %>
  </p>

  <p>
    <strong>Task:</strong>
    <%= comment.task.title %>
  </p>

  <p>
    <strong>Task:</strong>
    <%= comment.task.project.name %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: [task, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h4><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.label :author_name, style: "display: block" %>
    <%= form.text_field :author_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Comments" %>

<div>
  <%= link_to "Back to landing", root_path %>
</div>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <div class="element">
      <%= render comment %>
    </div>
  <% end %>
</div>

app/views/comments/new.html.erb
<% content_for :title, "New comment" %>

<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Task Tracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/landing.html.erb
<h1>Task Tracker</h1>

<%= link_to "projects", projects_path %>
<%= link_to "tasks", tasks_path %>
<%= link_to "comments", comments_path %>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h4><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h4>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projects" %>

<div>
  <%= link_to "Back to landing", root_path %>
  <%= link_to "New project", new_project_path %>
</div>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <div class="element">
      <%= render project %>
      <p>
        <%= link_to "Show this project", project %>
      </p>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

<h1><%= @project.name %></h1>
<p><%= @project.description %></p>

<h2>Tasks</h2>

<!-- filters -->
<div>
  <%= link_to "All", project_path(@project) %>
  <%= link_to "Todo", project_path(@project, status: 'todo', priority: params[:priority]) %>
  <%= link_to "In Progress", project_path(@project, status: 'in_progress', priority: params[:priority]) %>
  <%= link_to "Done", project_path(@project, status: 'done', priority: params[:priority]) %>

  <%= link_to "Priority 1", project_path(@project, priority: 1, status: params[:status]) %>
  <%= link_to "Priority 2", project_path(@project, priority: 2, status: params[:status]) %>
  <%= link_to "Priority 3", project_path(@project, priority: 3, status: params[:status]) %>
  <%= link_to "Priority 4", project_path(@project, priority: 4, status: params[:status]) %>
  <%= link_to "Priority 5", project_path(@project, priority: 5, status: params[:status]) %>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>  
      <th>Due Date</th>
      <th>Priority</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @tasks&.any? %>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.status %></td>
          <td><%= task.due_date&.strftime("%B %d, %Y") || "- no due date -"%></td>
          <td><%= task.priority %></td>
          <td>
            <%= link_to "View", task_path(task) %>

            <% unless task.status == 'done' %>
              <%= button_to "#{task.status == 'todo' ? 'Start' : 'Done'}", 
                project_task_path(@project, task), 
                method: :patch,
                params: { task: { status: task.status == 'todo' ? 'in_progress' : 'done' } } 
              %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h2>add task</h2>

<%= render "tasks/form", task: @task, project: @project %>

app/views/tasks/_form.html.erb
<%= form_with(model: [project, task]) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h4><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h4>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, 
      options_for_select(Task.statuses.map {|key, value| [key.humanize, key]}, @task.status),
      { prompt: "Select status" },
      { class: "form-select" } %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    <%= form.label :priority, style: "display: block" %>
    <%= form.number_field :priority %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= task.status %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= task.due_date %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= task.priority %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= task.project.name %>
  </p>

</div>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing task" %>

<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Tasks" %>

<div>
  <%= link_to "Back to landing", root_path %>
</div>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <div class="element">
      <%= render task %>
      <p>
        <%= link_to "Show this task", task %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<% content_for :title, "New task" %>

<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

<h1>task</h1>

<%= render @task %>

<h2>comments</h2>
<% unless @comments.empty? %>
  <table>
    <thead>
      <tr>
        <th>Body</th>
        <th>Author</th>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.body %></td>
          <td><%= comment.author_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No comments</p>
<% end %>

<h2>add comment</h2>

<%= render "comments/form", comment: @comment, task: @task %>